name: CI

on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Sanity check
        run: |
          echo "Repo content:"
          ls -la
          echo ""
          echo "Java version:"
          java -version
          echo ""
          echo "README exists?"
          test -f README.md && echo "OK" || (echo "Missing README.md" && exit 1)

      - name: Run Java tests (Maven)
        run: |
          if [ -f "java/hello-junit/pom.xml" ]; then
            cd java/hello-junit
            mvn -q test
          else
            echo "No Maven project found in java/hello-junit â€” skipping."
          fi

      - name: Run API tests (Postman/Newman)
        run: |
          npm install -g newman
          newman run api/postman/httpbin.postman_collection.json
          